# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
